SecResponseBodyAccess Off

SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLog /var/log/modsecurity/modsec_audit.log

SecDebugLog /var/log/modsecurity/modsec_debug.log
SecDebugLogLevel 1

#SecServerSignature "Apache" el conector v3 / investigar esto despues
SecUnicodeMapFile /etc/modsecurity.d/unicode.mapping 20127
SecTmpDir /tmp/
SecDataDir /tmp/

# OWASP CRS configuration
Include /etc/nginx/modsecurity.d/owasp-crs/crs-setup.conf
Include Include /opt/owasp-crs/rules/*.conf
